# Generated by Django 5.0.6 on 2024-08-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogHome', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField()),
                ('created', models.DateField(auto_now=True)),
                ('blogparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogHome.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('Reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('commentparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogHome.comment')),
            ],
        ),
    ]
